services:
  db:
    image: mongo:8.0.4-rc0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nullSkillz42
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
  # backend:
  #   build:
  #     dockerfile: './backend/Dockerfile'
  #   restart: always
  #   ports:
  #     - '3000:3000'
    # environment:
    #   - NODE_ENV=production
    #   - PORT=3000
    #   - SERVICE_NAME=neznan-app/backend
    #   - JWT_SECRET=secret
    #   - DATABASE_URL=mongodb://root:nullSkillz42@db:27017
    #   - EXTERNAL_URL=http://localhost:3000
    #   - FRONTEND_URL=http://localhost:8080
    #   - LOG_LEVEL=silly
    #   - API_PREFIX=/v1
    #   - TZ=Europe/Ljubljana
    # depends_on:
    #   - db
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.local
  #   restart: always
  #   ports:
  #     - '8080:80'

volumes:
  mongodb_data:
